### ISSUE TITLE
FB.getLoginUrl() not working with some of the scope

### ISSUE THREAD

**Issue by rolljee** [node-facebook/facebook-node-sdk#133]
# Getting facebook api working with meteor

## The request i made
FB.getLoginUrl({ scope: 'email,user_videos,user_posts,publish_actions', redirect_uri: Meteor.absoluteUrl('facebook') });

## The response i got
"https://www.facebook.com/v2.3/dialog/oauth?response_type=code&scope=email%2Cuser_videos%2Cuser_posts%2Cpublish_actions&redirect_uri=https%3A%2F%2F<website>%2Ffacebook&client_id=XxxxxxXXXXXxxxxx"

## The probleme i have

![screen shot 2018-02-13 at 17 00 07](https://user-images.githubusercontent.com/10114634/36159608-660f4282-10df-11e8-80d1-dba64d41f638.png)

It is saying that the app cannot publish on the user page, event i explicitly asked for the publish_actions scope.

Can someone tell me if i am doing something wrong here ?

**Comment by dantman** [comment]
It looks like the SDK is working fine since you're getting the right url to send the user to.

You've only given the getLoginUrl call you make so I have no clue what the problem with your code is.

General support for using the Graph API should go to [Stack Overflow](https://stackoverflow.com/questions/tagged/facebook).
