### ISSUE TITLE
appSecretProof is null?

### ISSUE THREAD

**Issue by JonesWest** [node-facebook/facebook-node-sdk#174]
Hi, 

I do the following to initialize the the facebook module: 

```
    FB.api('oauth/access_token', {
        client_id: '...',
        client_secret: '...',
        grant_type: 'client_credentials'
    }, function (res) {
        facebookAccessToken = res.access_token;
        FB.options({
            version: "v3.2",
            accessToken: facebookAccessToken
        });

        console.log(FB.options())
    });
```
But then it troubles me that the options output says: 

`{ accessToken: '...',
  appSecretProof: null,
  version: 'v3.2' }`

Why is the appSecretProof = null? At the moment we're getting warnings from facebook that we should update the facebook API. One of the changes Facebook says we will experience on a number of API calls soon is: 

> Starts enforcing the app's restrictions (such as country or age ) on API calls made without the application's ' appsecret_proof'in the request.

Which makes sense if we're not sending the appSecretProof at all?

**Comment by dantman** [comment]
The `appSecretProof` option is an old option for user specified proofs. When it's not specified the proof is automatically generated https://github.com/node-facebook/facebook-node-sdk/blob/master/src/fb.js#L347-L356.

It looks like your issue is probably that you are not defining an appId and appSecret in the options. You should be defining the version/appId/appSecret options BEFORE making the FB.api call, not inside of it. You're basically making a v2.5 API call and then updating the version setting to v3.2 instead of always calling the v3.2 API.

**Comment by JonesWest** [comment]
@dantman OK thank you - I will try that :-)
