### ISSUE TITLE
Breaking Change

### ISSUE THREAD

**Issue by billinghamj** [node-facebook/facebook-node-sdk#54]
When you converted to using a class internally, using FB with Q's nfcall stopped working. Probably due to the `this` binding now being important.

Previously I could do this:

```js
await Q.nfcall(FB.napi, 'me');
```

Following your changes, this would be required instead:

```js
await Q.ninvoke(FB, 'napi', 'me');
```

The latter version calls `napi` setting `this` to `FB`.

Might be worth providing some kind of shim to handle this issue, possibly binding the functions for the default & FB exports.

**Comment by dantman** [comment]
This actually only seems to be a problem if you create your own instance or use an ES6 `import` with Babel; since the CommonJS `exports` object contains bound methods. However I'll fix this since I made this change in a minor release.

To be honest though, that kind of code will be completely unnecessary in `2.0.0` since Promises are supported natively.
```js
FB.options({
  Promise: Q.Promise
});
// ...
await FB.api('me');
```

**Comment by billinghamj** [comment]
Indeedy, I have since moved to v2. Just unfortunately it broke several of my services which were relying on ^1.0.0
