### ISSUE TITLE
Upload with Buffer 

### ISSUE THREAD

**Issue by gregory-h** [node-facebook/facebook-node-sdk#62]
Is there a working example of using a buffer for image upload?  The docs indicate to use source: { value: buffer.. }, but the unit tests use file: { value: buffer }..

I assume the file: { value: buffer..} syntax is correct, but I have a base64 encoded image to upload and can't get it to work using either syntax.  This should work. 

fb.api( 'myPageId'/photos', 'post', { 
      caption: 'my caption', , 
      file: { 
        value: new Buffer( data, 'base64'), 
        options: { contentType: 'image/jpeg' } 
      } 
    }, function(response) {})

I'm using the  1.1 branch.  Is there an expectation for the buffer encoding? 

Thx,

**Comment by dantman** [comment]
File uploads are `1.1.0+`.

`file` and `source` are both valid, file upload handling applies to all parameter values using one of the file syntaxes; and Facebook doesn't care about the parameter name ([docs](https://developers.facebook.com/docs/graph-api/reference/page/photos/#Creating)), it just takes whatever parameter you happen to post a file upload to.

**Comment by gregory-h** [comment]
I have 1.1.1 installed, and the file and source syntax both return #324 'upload file required'.

I'm working around it by writing the base64 to the filesystem and then uploading it using the source: fs.createReadStream() syntax; is there a particular buffer encoding that is expected? 

Thx,

**Comment by dantman** [comment]
The 'right' base64 encoding is Node.js' scope. `Buffer` is a Node.js API and when you `new Buffer(..., 'base64')` Node.js is responsible for decoding the string and the result is a "Buffer" object containing the raw binary data. So to libraries using Buffer are completely agnostic to what encoding you use to create the Buffer.

`fb`'s role is relatively simple, if any parameter value is an object that looks like a file stream, a buffer, or is an object that contains a `value` that is a Buffer and an `options`; then the post data object is passed to [request](https://www.npmjs.com/package/request) as `{formData: ...}` instead of as `{form: ...}`.

That makes `request` use `multipart/form-data` and the `form-data` library to include parameters with certain patterns as file uploads.

----

Does including a `filename` parameter in your `options` object change anything?

**Comment by gregory-h** [comment]
It does - base64 encoding with a filename solves it. 
Thanks Daniel.

**Comment by matteocontrini** [comment]
For anyone having the same issue, the solution is adding a `filename` option, as mentioned above.

```js
let params = {
	source: {
		value: yourBuffer,
		options: { contentType: 'image/jpeg', filename: 'something.jpg' }
	},
	caption: 'Hello'
};

fb.api('me/photos', 'post', params, (err, res) => {
	console.log(err);
	console.log(res);
});
```
