### ISSUE TITLE
Unexpected token error in SyntaxErrorReporter of core-decorators

### ISSUE THREAD

**Issue by meilers** [node-facebook/facebook-node-sdk#73]
I'm getting the following error when I try to import the library in a react project.

`import FB from 'fb';
`

![screen shot 2016-10-12 at 10 21 39 am](https://cloud.githubusercontent.com/assets/2792041/19321856/ac6e20cc-9084-11e6-8ccb-33b8d0d68413.png)

Any ideas? I'm using the ES2015 preset.

**Comment by dantman** [comment]
You'll need to give me more details about how you are transpiling your code.

`fb` imports `core-decorators` at the package level and core-decorator's `main` points to the `lib/` folder, you only get `src/` if you are using a bundler that uses `jsnext:main` instead.
*(Strictly speaking, that means any actual bug is a bug in `core-decorators`, not `fb`)*

The only other helpful note I can give you is that the class property syntax (`class { foo = 'bar'; }` and `class { foo; }`) aren't `es6`/`es2015` they are `stage-2`. Decorators themselves are `stage-2`. And core-decorators advertises it as a `stage-0` package.

If you are relying on `jsnext:main`, I'd recommend either adding the `stage-0` preset to your transpiler or open a bug in `core-decorators` asking them transpile their `src/` folder with `stage-0` and `es2015` - modules or at least `stage-0`. Since as I recall `jsnext:main`/`modules` is only supposed to contain es5 + es6-modules.
